
mysql:
  host: localhost
  port: 3306
  serverTimezone: Europe/Berlin
  database: DataHorizontal
  table: deletions
  url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=${mysql.serverTimezone}
  connection:
    user: root
    password: root
    driver: com.mysql.cj.jdbc.Driver

app:
  file:
    path: deletions-sample/sample-data.csv

spark:
  name: Importer Application
  uri: local[1]

spring:
  banner:
    location: banner.txt

logging:
  level:
    org.apache.spark: ERROR
    org.spark_project.jetty: ERROR